#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.
url                                       : https://simpleip.arandabar.com

# App Info
ios_app_id                                : 1610102699                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : /assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Simply IP - Show my IP                       # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : FREE                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Get your Public IP and private IP at a glance, with a simple and beautiful interface.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Giovanny Aranda                                
your_link                                 :                     
your_city                                 : Madrid                                
email_address                             : 
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Get your Public IP
    description                           : Shows your ISP or VPN Public IP
    fontawesome_icon_name                 : network-wired
    
  - title                                 : Interface network address
    description                           : Shows your network interface private IP
    fontawesome_icon_name                 : shield-alt

  - title                                 : Notifications
    description                           : Get a macOS notification when your public IP change
    fontawesome_icon_name                 : bell

  - title                                 : IP Location
    description                           : If available, get location flag from your public IP
    fontawesome_icon_name                 : map-marker-alt

  - title                                 : Update
    description                           : Choose to update your information every certain minutes
    fontawesome_icon_name                 : redo

  - title                                 : Dark mode
    description                           : A native dark mode experience use it automatically starting iOS 13.
    fontawesome_icon_name                 : moon
     



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#000000"

link_color                                : "#ffd41b"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#ffd41b"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#ffffff"
feature_icons_background_color            : "#666666"

social_icons_foreground_color             : "#ffffff"
social_icons_background_color             : "#666666"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
